// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class department
    {
        public int id { get; set; }
        public string dep_name { get; set; }
        public string dep_description { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? updated_date { get; set; }
        public string updated_by { get; set; }
    }
}