// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class employees
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string picPath { get; set; }
        public string userAD { get; set; }
        public string status { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? updated_date { get; set; }
        public string updated_by { get; set; }
        public int? regisID { get; set; }
        public int? depID { get; set; }

        public virtual register regis { get; set; }
    }
}