// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class gallerySub
    {
        public int id { get; set; }
        public string imgSub_Path { get; set; }
        public int? imgMain_ID { get; set; }
        public int? created_by { get; set; }
        public DateTime? created_date { get; set; }
    }
}