// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class galleryMain
    {
        public int id { get; set; }
        public int? topicType { get; set; }
        public string topicDetail { get; set; }
        public int? created_by { get; set; }
        public DateTime? created_date { get; set; }
        public string imgMain_Path { get; set; }
    }
}