// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class group
    {
        public int id { get; set; }
        public int? regisID { get; set; }
        public int? authenID { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? updated_date { get; set; }
        public string updated_by { get; set; }
        public bool? isDelete { get; set; }
    }
}