// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class news
    {
        public int id { get; set; }
        public string headNews { get; set; }
        public string contentShort { get; set; }
        public string contentAll { get; set; }
        public string imagePath { get; set; }
        public string videoPath { get; set; }
        public string created_by { get; set; }
        public DateTime? created_date { get; set; }
        public int? depID { get; set; }
    }
}