// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class register
    {
        public register()
        {
            employees = new HashSet<employees>();
        }

        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string confirm_password { get; set; }
        public DateTime? created_date { get; set; }
        public string created_by { get; set; }
        public DateTime? updated_date { get; set; }
        public string updated_by { get; set; }
        public bool? isDelete { get; set; }

        public virtual ICollection<employees> employees { get; set; }
    }
}