// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class topicGallary
    {
        public int id { get; set; }
        public string topicGallery { get; set; }
        public int? created_by { get; set; }
        public DateTime? created_date { get; set; }
        public int? depID { get; set; }
    }
}