// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class uploadFileKM
    {
        public int id { get; set; }
        public string subject_km { get; set; }
        public string detail_km { get; set; }
        public string pdfPath { get; set; }
        public string videoPath { get; set; }
        public bool? isDelete { get; set; }
        public int? created_by { get; set; }
        public DateTime? created_date { get; set; }
        public int? depID { get; set; }
    }
}