// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RestAPIDemo
{
    public partial class uploadFileMenu
    {
        public int id { get; set; }
        public string subject { get; set; }
        public string filePath { get; set; }
        public string URLPath { get; set; }
        public string videoPath { get; set; }
        public int? isDelete { get; set; }
        public int? created_by { get; set; }
        public DateTime? created_date { get; set; }
        public int? menuID { get; set; }
    }
}